export const LOGIN_SCREEN = 'LOGIN_SCREEN';

export const TABS_SCREEN = 'TABS_SCREEN';

export const PROFILE_TAB = 'PROFILE_TAB';
export const PROFILE = 'PROFILE_SCREEN';

export const BOOK_TAB = 'BOOK_TAB';
export const LIST_BOOK_SCREEN = 'LIST_BOOK_SCREEN';
export const BOOKS_INFORMATION_SCREEN = 'BOOKS_INFORMATION_SCREEN';
